# Generated by Django 3.2.3 on 2021-06-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ManyToManyField(related_name='store_items', to='shop.Store'),
        ),
    ]
