# Generated by Django 3.2.3 on 2021-06-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210623_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_replaceable',
            field=models.BooleanField(default=False),
        ),
    ]
